-- Admin notifications table (MVP)
create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null default 'system',
  title text not null,
  message text not null,
  link text null,
  metadata jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  created_at timestamp with time zone not null default now(),
  read_at timestamp with time zone null
);

create index if not exists idx_admin_notifications_user_created
  on public.admin_notifications (user_id, created_at desc);

create index if not exists idx_admin_notifications_user_unread
  on public.admin_notifications (user_id, is_read, created_at desc);
